builds:
- env:
  - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - github:
      owner: robscott
      name: homebrew-tap
    folder: Formula
    description: kube-capacity provides an overview of the resource requests, limits, and utilization in a Kubernetes cluster
    test: |
      system "#{bin}/kube-capacity version"  
