version: 2

jobs:
  test:
    working_directory: /go/src/github.com/robscott/kube-capacity

    docker:
      - image: circleci/golang:1.13

    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: go list ./... | grep -v vendor | xargs golint -set_exit_status
      - run: go list ./... | grep -v vendor | xargs go vet
      - run: go test ./pkg/... -v -coverprofile cover.out

  release:
    working_directory: /go/src/github.com/robscott/kube-capacity
    
    docker:
      - image: circleci/golang:1.13

    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  main:
    jobs:
      - test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/