version: 2

jobs:
  test:
    working_directory: /go/src/github.com/robscott/kube-capacity

    docker:
      - image: circleci/golang:1.13

    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: go list ./... | grep -v vendor | xargs golint -set_exit_status
      - run: go list ./... | grep -v vendor | xargs go vet
      - run: go test ./pkg/... -v -coverprofile cover.out
  
  release:
    working_directory: /go/src/github.com/robscott/kube-capacity

    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

  update-krew-index:
    working_directory: /go/src/github.com/robscott/kube-capacity
    
    docker:
      - image: ubuntu:latest
        environment:
          GITHUB_REPOSITORY: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
          GITHUB_ACTOR: ${CIRCLE_USERNAME}
          KREW_RELEASE_BOT_WEBHOOK_URL: https://krew-release-bot-dryrun.rajatjindal.com/github-action-webhook
          GITHUB_WORKSPACE: ${CIRCLE_WORKING_DIRECTORY}
          GITHUB_REF: refs/tags/${CIRCLE_TAG}

    steps:
      - run: apt-get update && apt-get install curl -y
      - run: curl -LO https://github.com/rajatjindal/krew-release-bot/releases/download/v0.0.34-3/krew-release-bot_v0.0.34-3_linux_amd64.tar.gz
      - run: tar -xvf krew-release-bot_v0.0.34-3_linux_amd64.tar.gz
      - run: ls -ltr
      - run: pwd
      - run: printenv

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      
      - release:
        # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

      - update-krew-index:
          requires:
            - release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/